# Validation

In [1]:
import pandas as pd

In [2]:
# Paths
PATH = '/home/tatiane/repositorios/brazil-health-data-project/data_pipeline'
conversion_path = f"{PATH}/data/processed/ibge_codigos/01_conversion/dtb_brasil_2024_municipios.parquet"
standardization_path = f"{PATH}/data/processed/ibge_codigos/02_standardization/dtb_br_2024_municipios.parquet"

In [3]:
# Reading
conversion = pd.read_parquet(conversion_path)
standardization = pd.read_parquet(standardization_path)

- Validation

In [7]:
resumo_conversion = pd.DataFrame({
    'tipo': conversion.dtypes,
    'nulos': conversion.isnull().sum(),
    'perc_nulos': (conversion.isnull().sum() / len(conversion)) * 100,
    'unicos': conversion.nunique()
})

resumo_conversion

                                        tipo  nulos  perc_nulos  unicos
UF                                     int64      0     0.00000      27
Nome_UF                               object      0     0.00000      27
Região Geográfica Intermediária        int64      0     0.00000     133
Nome Região Geográfica Intermediária  object      0     0.00000     133
Região Geográfica Imediata             int64      0     0.00000     510
Nome Região Geográfica Imediata       object      0     0.00000     508
Município                              int64      0     0.00000    4308
Código Município Completo              int64      0     0.00000    5571
Nome_Município                        object      0     0.00000    5298
Unnamed: 9                            object   5570    99.98205       1

In [8]:
resumo_standardization = pd.DataFrame({
    'tipo': standardization.dtypes,
    'nulos': standardization.isnull().sum(),
    'perc_nulos': (standardization.isnull().sum() / len(standardization)) * 100,
    'unicos': standardization.nunique()
})

resumo_standardization

                    tipo  nulos  perc_nulos  unicos
cod_uf             int64      0         0.0      27
nm_uf             object      0         0.0      27
reg_geo_inter      int64      0         0.0     133
nm_reg_geo_inter  object      0         0.0     133
reg_geo_imed       int64      0         0.0     510
nm_reg_geo_imed   object      0         0.0     508
municipio          int64      0         0.0    4308
cod_mun_comp       int64      0         0.0    5571
nm_mun            object      0         0.0    5298