# Ingestion and Integrity Validation

- Format and Schema Verification: Confirm that the data is in its original format (JSON, CSV, Parquet) and that the column names and data types match the initial expectation.
- Row Count: Compare the number of rows received with the number of rows sent by the source to ensure that there was no data loss during transport.
- Corruption Check: Check if the files are not corrupted or incomplete (files with a size of 0 or less).
- Identificação de Nulos: Verificar se campos obrigatórios (primary keys, IDs) estão vindo como null.

In [1]:
import pandas as pd

In [2]:
# Leitura

PATH = '/home/tatiane/repositorios/brazil-health-data-project/data_pipeline'
df = pd.read_csv(f"{PATH}/data/raw/ibge_populacao/tabela6579.csv", sep=";", skiprows=3)

In [3]:
print('Quantidade de registros e colunas:' , df.shape)

Quantidade de registros e colunas: (5774, 6)

In [4]:
resumo = pd.DataFrame({
    'tipo': df.dtypes,
    'nulos': df.isnull().sum(),
    'perc_nulos': (df.isnull().sum() / len(df)) * 100,
    'unicos': df.nunique()
})

resumo

                                    tipo  nulos  perc_nulos  unicos
Cód.                              object      1    0.017319    5761
Unidade da Federação e Município  object    169    2.926914    5605
2018                              object    176    3.048147    5122
2019                              object    176    3.048147    5104
2020                              object    176    3.048147    5150
2021                              object    176    3.048147    5137

In [5]:
df.head()

  Cód. Unidade da Federação e Município     2018     2019     2020     2021
0   11                         Rondônia  1757589  1777225  1796460  1815278
1   12                             Acre   869265   881935   894470   906876
2   13                         Amazonas  4080611  4144597  4207714  4269995
3   14                          Roraima   576568   605761   631181   652713
4   15                             Pará  8513497  8602865  8690745  8777124