# Ingestion and Integrity Validation

- Format and Schema Verification: Confirm that the data is in its original format (JSON, CSV, Parquet) and that the column names and data types match the initial expectation.
- Row Count: Compare the number of rows received with the number of rows sent by the source to ensure that there was no data loss during transport.
- Corruption Check: Check if the files are not corrupted or incomplete (files with a size of 0 or less).
- Identificação de Nulos: Verificar se campos obrigatórios (primary keys, IDs) estão vindo como null.

In [2]:
import pandas as pd

In [3]:
# Leitura

PATH = '/home/tatiane/repositorios/brazil-health-data-project/data_pipeline'
df = pd.read_csv(f"{PATH}/data/raw/ibge_pnad_continua/tabela5436.csv",
    sep=",",
    encoding="latin1",
    #skiprows=10  # remove cabeçalho do SIDRA
)

In [5]:
print('Quantidade de registros e colunas:' , df.shape)

Quantidade de registros e colunas: (27, 14)

In [4]:
resumo = pd.DataFrame({
    'tipo': df.dtypes,
    'nulos': df.isnull().sum(),
    'perc_nulos': (df.isnull().sum() / len(df)) * 100,
    'unicos': df.nunique()
})

resumo

                          tipo  nulos  perc_nulos  unicos
ï»¿CÃ³d.                 int64      0         0.0      27
Unidade da FederaÃ§Ã£o  object      0         0.0      27
1Âº trimestre 2018       int64      0         0.0      27
2Âº trimestre 2018       int64      0         0.0      27
3Âº trimestre 2018       int64      0         0.0      27
4Âº trimestre 2018       int64      0         0.0      26
1Âº trimestre 2019       int64      0         0.0      27
2Âº trimestre 2019       int64      0         0.0      26
3Âº trimestre 2019       int64      0         0.0      27
4Âº trimestre 2019       int64      0         0.0      27
1Âº trimestre 2020       int64      0         0.0      27
2Âº trimestre 2022       int64      0         0.0      27
3Âº trimestre 2022       int64      0         0.0      27
4Âº trimestre 2022       int64      0         0.0      27

In [7]:
df.head()

,ï»¿CÃ³d.,Unidade da FederaÃ§Ã£o,1Âº trimestre 2018,2Âº trimestre 2018,3Âº trimestre 2018,4Âº trimestre 2018,1Âº trimestre 2019,2Âº trimestre 2019,3Âº trimestre 2019,4Âº trimestre 2019,1Âº trimestre 2020,2Âº trimestre 2022,3Âº trimestre 2022,4Âº trimestre 2022
0,11,RondÃ´nia,2699,2663,2787,2719,2601,2622,2739,2709,2662,2658,2755,2900
1,12,Acre,2352,2401,2466,2476,2578,2544,2510,2595,2461,2641,2587,2538
2,13,Amazonas,2442,2439,2321,2277,2335,2288,2352,2294,2320,2258,2333,2409
3,14,Roraima,3185,3059,3011,2976,2935,3136,3146,2926,2995,2708,2602,2936
4,15,ParÃ¡,2109,2063,2096,2052,2082,2027,2093,2156,2113,2125,2217,2243